import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

interface SeedQuestion {
  courseSlug: "html" | "css" | "javascript";
  topicName: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  type: "mcq";
  question: string;
  code?: string | null;
  options: string[];
  correctAnswer: string;
  explanation: string;
}

const RICH_QUESTIONS: SeedQuestion[] = [
  // ===================== HTML QUESTIONS =====================
  {
    courseSlug: "html",
    topicName: "HTML Basics",
    difficulty: "EASY",
    type: "mcq",
    question: "What does the abbreviation HTML stand for?",
    options: [
      "HyperText Markup Language",
      "HighText Machine Language",
      "HyperText Markdown Language",
      "HyperTool Multi Language",
    ],
    correctAnswer: "HyperText Markup Language",
    explanation: "HTML stands for HyperText Markup Language, the standard authoring language used to create web pages.",
  },
  {
    courseSlug: "html",
    topicName: "HTML Basics",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which of the following describes the difference between an HTML tag and an HTML element?",
    options: [
      "An element consists of the start tag, content, and the end tag, while a tag is just the delimiter (<tag> or </tag>)",
      "A tag contains attributes, while an element cannot contain attributes",
      "An element is always self-closing, while a tag requires both opening and closing",
      "There is no distinction between tag and element in HTML specification",
    ],
    correctAnswer: "An element consists of the start tag, content, and the end tag, while a tag is just the delimiter (<tag> or </tag>)",
    explanation: "An HTML element encompasses the opening tag, attributes, enclosed content, and the closing tag.",
  },
  {
    courseSlug: "html",
    topicName: "HTML Basics",
    difficulty: "HARD",
    type: "mcq",
    question: "What happens if a browser encounters an unrecognized custom HTML tag such as <my-widget> without Web Component registration?",
    options: [
      "The browser treats it as an inline HTMLUnknownElement and renders its children normally",
      "The browser halts rendering and throws a fatal DOM parsing exception",
      "The browser removes the element and drops all child content",
      "The browser automatically converts it to an empty <div> block",
    ],
    correctAnswer: "The browser treats it as an inline HTMLUnknownElement and renders its children normally",
    explanation: "Standard browsers parse unknown tags as HTMLUnknownElement (or HTMLElement for valid custom element names) and display their contents as inline elements.",
  },
  {
    courseSlug: "html",
    topicName: "HTML Document Structure",
    difficulty: "EASY",
    type: "mcq",
    question: "Which HTML tag is used to store metadata such as title, character encoding, and stylesheets?",
    options: ["<head>", "<body>", "<meta-container>", "<header>"],
    correctAnswer: "<head>",
    explanation: "The <head> element contains machine-readable information (metadata) about the document, like its title, scripts, and style sheets.",
  },
  {
    courseSlug: "html",
    topicName: "HTML Document Structure",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Why must '<!DOCTYPE html>' be the very first line in an HTML5 document?",
    options: [
      "To force the browser into full standards compliance mode and prevent quirks mode",
      "To load the official W3C schema definitions over HTTP",
      "To inform the server which compression algorithm to use",
      "To enable JavaScript execution in the browser runtime",
    ],
    correctAnswer: "To force the browser into full standards compliance mode and prevent quirks mode",
    explanation: "<!DOCTYPE html> tells the browser to parse the document in strict standards mode rather than legacy quirks mode.",
  },
  {
    courseSlug: "html",
    topicName: "Elements",
    difficulty: "EASY",
    type: "mcq",
    question: "Which of the following is a void (self-closing) element in HTML5?",
    options: ["<br>", "<p>", "<div>", "<span>"],
    correctAnswer: "<br>",
    explanation: "<br>, <img>, <hr>, <input>, and <meta> are void elements and cannot have closing tags or child nodes.",
  },
  {
    courseSlug: "html",
    topicName: "Elements",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which element represents preformatted text where whitespace and line breaks are preserved exactly as written?",
    options: ["<pre>", "<code>", "<samp>", "<kbd>"],
    correctAnswer: "<pre>",
    explanation: "The <pre> element presents text in a fixed-pitch font and preserves spaces, tabs, and line breaks.",
  },
  {
    courseSlug: "html",
    topicName: "Attributes",
    difficulty: "EASY",
    type: "mcq",
    question: "Which global attribute is used to provide a tooltip description when the user hovers over an element?",
    options: ["title", "tooltip", "hover", "desc"],
    correctAnswer: "title",
    explanation: "The global 'title' attribute represents advisory information, typically shown as a tooltip on hover.",
  },
  {
    courseSlug: "html",
    topicName: "Attributes",
    difficulty: "HARD",
    type: "mcq",
    question: "Which attribute prefix allows authors to embed custom data private to the page or application on any HTML element?",
    options: ["data-*", "custom-*", "attr-*", "var-*"],
    correctAnswer: "data-*",
    explanation: "The 'data-*' attribute format allows custom data storage accessible via the dataset DOM property in JavaScript.",
  },
  {
    courseSlug: "html",
    topicName: "Headings",
    difficulty: "EASY",
    type: "mcq",
    question: "Which tag defines the highest-level, most important heading on an HTML web page?",
    options: ["<h1>", "<h6>", "<header>", "<head>"],
    correctAnswer: "<h1>",
    explanation: "<h1> defines the most important heading. Web pages should generally have a single <h1> describing the document.",
  },
  {
    courseSlug: "html",
    topicName: "Headings",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Why should heading levels (h1 through h6) not be skipped (e.g. going directly from h1 to h3)?",
    options: [
      "Skipping levels breaks document outline accessibility for screen reader navigation",
      "Browsers fail to render skipped heading levels properly",
      "Skipping headings causes a fatal HTML validation syntax error",
      "CSS styles cannot be applied if heading levels are skipped",
    ],
    correctAnswer: "Skipping levels breaks document outline accessibility for screen reader navigation",
    explanation: "Screen readers rely on hierarchical heading structures (h1 -> h2 -> h3) to allow visually impaired users to scan the document outline.",
  },
  {
    courseSlug: "html",
    topicName: "Paragraphs",
    difficulty: "EASY",
    type: "mcq",
    question: "What element defines a block of text as a paragraph in HTML?",
    options: ["<p>", "<para>", "<text>", "<pg>"],
    correctAnswer: "<p>",
    explanation: "The <p> element represents a paragraph of text, automatically inserting vertical margins before and after in user-agent stylesheets.",
  },
  {
    courseSlug: "html",
    topicName: "Links",
    difficulty: "EASY",
    type: "mcq",
    question: "Which attribute in the <a> tag specifies the destination URL of a hyperlink?",
    options: ["href", "src", "link", "target"],
    correctAnswer: "href",
    explanation: "'href' (Hypertext REFerence) specifies the URL of the page or resource the link goes to.",
  },
  {
    courseSlug: "html",
    topicName: "Links",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "When opening external links with target='_blank', which rel values should be added to prevent security and performance vulnerabilities?",
    options: [
      "rel='noopener noreferrer'",
      "rel='nofollow noindex'",
      "rel='external safe'",
      "rel='secure target'",
    ],
    correctAnswer: "rel='noopener noreferrer'",
    explanation: "noopener prevents the new page from accessing window.opener, protecting against malicious redirects and process thread blocking.",
  },
  {
    courseSlug: "html",
    topicName: "Images",
    difficulty: "EASY",
    type: "mcq",
    question: "Which attribute is mandatory on an <img> element for web accessibility and screen readers?",
    options: ["alt", "title", "caption", "name"],
    correctAnswer: "alt",
    explanation: "The alt attribute provides alternative text for screen readers and displays when the image fails to load.",
  },
  {
    courseSlug: "html",
    topicName: "Images",
    difficulty: "HARD",
    type: "mcq",
    question: "What is the purpose of the 'srcset' and 'sizes' attributes on an <img> element?",
    options: [
      "They enable responsive images, allowing the browser to select the optimal image asset based on device pixel ratio and viewport width",
      "They animate the image through CSS transitions",
      "They apply client-side image compression before rendering",
      "They enforce strict width-to-height aspect ratios across all devices",
    ],
    correctAnswer: "They enable responsive images, allowing the browser to select the optimal image asset based on device pixel ratio and viewport width",
    explanation: "srcset defines candidate image sources with pixel densities or widths, and sizes specifies layout width conditions.",
  },
  {
    courseSlug: "html",
    topicName: "Lists",
    difficulty: "EASY",
    type: "mcq",
    question: "Which HTML tag is used to create an unordered (bulleted) list?",
    options: ["<ul>", "<ol>", "<li>", "<dl>"],
    correctAnswer: "<ul>",
    explanation: "<ul> defines an unordered list, typically displayed with bullets, containing <li> elements.",
  },
  {
    courseSlug: "html",
    topicName: "Lists",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which element is used to describe a term within an HTML description list (<dl>)?",
    options: ["<dt>", "<dd>", "<li>", "<term>"],
    correctAnswer: "<dt>",
    explanation: "In a description list (<dl>), <dt> specifies the term or name, and <dd> specifies the description or value.",
  },
  {
    courseSlug: "html",
    topicName: "Tables",
    difficulty: "EASY",
    type: "mcq",
    question: "Which tag defines a header cell in an HTML table, displayed bold and centered by default?",
    options: ["<th>", "<td>", "<tr>", "<thead-cell>"],
    correctAnswer: "<th>",
    explanation: "<th> defines a table header cell, conveying semantic header role to assistive technologies.",
  },
  {
    courseSlug: "html",
    topicName: "Tables",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which attribute allows a table cell to span horizontally across three columns?",
    options: ["colspan='3'", "rowspan='3'", "span='3'", "col-width='3'"],
    correctAnswer: "colspan='3'",
    explanation: "'colspan' indicates the number of columns a table cell should span across.",
  },
  {
    courseSlug: "html",
    topicName: "Forms",
    difficulty: "EASY",
    type: "mcq",
    question: "Which attribute on a <form> specifies the endpoint URL where form submission data is sent?",
    options: ["action", "method", "target", "href"],
    correctAnswer: "action",
    explanation: "The 'action' attribute contains the URI of a program or endpoint that handles the form data.",
  },
  {
    courseSlug: "html",
    topicName: "Forms",
    difficulty: "HARD",
    type: "mcq",
    question: "When creating a form that allows users to upload files (binary data), which enctype must be specified?",
    options: [
      "multipart/form-data",
      "application/x-www-form-urlencoded",
      "text/plain",
      "application/json",
    ],
    correctAnswer: "multipart/form-data",
    explanation: "multipart/form-data ensures binary file data is segmented and encoded properly for multi-part HTTP POST transmission.",
  },
  {
    courseSlug: "html",
    topicName: "Input Elements",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which input type renders a slider control allowing the user to select a number within a specified range?",
    options: ["type='range'", "type='slider'", "type='number'", "type='scale'"],
    correctAnswer: "type='range'",
    explanation: "type='range' displays a slider widget bound between 'min' and 'max' values.",
  },
  {
    courseSlug: "html",
    topicName: "Buttons",
    difficulty: "EASY",
    type: "mcq",
    question: "What is the default 'type' attribute of a <button> element inside a <form> if not explicitly specified?",
    options: ["submit", "button", "reset", "menu"],
    correctAnswer: "submit",
    explanation: "Inside a form, a <button> without a type attribute defaults to type='submit', which automatically triggers form submission when clicked.",
  },
  {
    courseSlug: "html",
    topicName: "Semantic HTML",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which HTML5 semantic element is most suitable for holding major site navigation links?",
    options: ["<nav>", "<menu>", "<aside>", "<section>"],
    correctAnswer: "<nav>",
    explanation: "The <nav> element represents a section of a page whose purpose is to provide navigation links (e.g. menus, tables of contents).",
  },
  {
    courseSlug: "html",
    topicName: "Semantic HTML",
    difficulty: "HARD",
    type: "mcq",
    question: "How does the <main> element differ from <article> and <section>?",
    options: [
      "<main> represents the dominant, central content unique to the document and must only appear once per rendered page",
      "<main> is an inline element used to style primary text",
      "<main> can appear multiple times within a single <header> or <footer>",
      "<main> is only permitted in XML documents",
    ],
    correctAnswer: "<main> represents the dominant, central content unique to the document and must only appear once per rendered page",
    explanation: "The <main> element contains content central to the document's purpose, excluding repeated items like sidebars, navbars, and copyright footers.",
  },
  {
    courseSlug: "html",
    topicName: "Classes",
    difficulty: "EASY",
    type: "mcq",
    question: "How are multiple CSS classes applied to a single HTML element?",
    options: [
      "Separate each class name with a space inside the class attribute: class='btn btn-primary'",
      "Separate each class with a comma: class='btn,btn-primary'",
      "Use multiple class attributes on the same tag: class='btn' class='btn-primary'",
      "Concatenate classes with plus signs: class='btn+btn-primary'",
    ],
    correctAnswer: "Separate each class name with a space inside the class attribute: class='btn btn-primary'",
    explanation: "Multiple class names in HTML are separated by a space character in the class attribute.",
  },
  {
    courseSlug: "html",
    topicName: "IDs",
    difficulty: "EASY",
    type: "mcq",
    question: "What is the primary constraint regarding the 'id' attribute in an HTML document?",
    options: [
      "The id must be strictly unique within the entire HTML document",
      "An id must be written in capital letters only",
      "An id can only be assigned to block-level elements",
      "An element can have up to three distinct id attributes",
    ],
    correctAnswer: "The id must be strictly unique within the entire HTML document",
    explanation: "The HTML specification requires that the id attribute value is unique across the entire document.",
  },

  // ===================== CSS QUESTIONS =====================
  {
    courseSlug: "css",
    topicName: "CSS Basics",
    difficulty: "EASY",
    type: "mcq",
    question: "What does the abbreviation CSS stand for?",
    options: [
      "Cascading Style Sheets",
      "Computer Style Sheets",
      "Creative Style System",
      "Colorful Sheet Syntax",
    ],
    correctAnswer: "Cascading Style Sheets",
    explanation: "CSS stands for Cascading Style Sheets, used to describe the presentation and layout of HTML documents.",
  },
  {
    courseSlug: "css",
    topicName: "CSS Basics",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which of the following describes the 'cascade' in CSS?",
    options: [
      "The algorithm that resolves conflicting rules based on origin, specificity, and source order",
      "The way child elements inherit font family properties from parents",
      "The automatic animation of dropdown navigation menus",
      "The sequential downloading of multiple external stylesheet files",
    ],
    correctAnswer: "The algorithm that resolves conflicting rules based on origin, specificity, and source order",
    explanation: "The cascade determines which declaration wins when multiple CSS rules target the same element.",
  },
  {
    courseSlug: "css",
    topicName: "Selectors",
    difficulty: "EASY",
    type: "mcq",
    question: "Which CSS selector syntax selects all elements with the class 'card'?",
    options: [".card", "#card", "*card", "card()"],
    correctAnswer: ".card",
    explanation: "In CSS, a period (.) denotes a class selector.",
  },
  {
    courseSlug: "css",
    topicName: "Selectors",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "What does the direct child combinator 'div > p' select?",
    options: [
      "All <p> elements that are direct, immediate children of a <div>",
      "All <p> elements located anywhere inside a <div>, including nested descendants",
      "The first <p> element that immediately follows a </div> in source code",
      "All <div> elements that contain at least one <p>",
    ],
    correctAnswer: "All <p> elements that are direct, immediate children of a <div>",
    explanation: "The child combinator (>) matches only elements that are immediate children of the specified parent element.",
  },
  {
    courseSlug: "css",
    topicName: "Selectors",
    difficulty: "HARD",
    type: "mcq",
    question: "What does the selector 'h2 ~ p' select in CSS?",
    options: [
      "All sibling <p> elements that follow an <h2> under the same parent element",
      "Only the single <p> element immediately following an <h2>",
      "All <p> elements nested inside an <h2>",
      "All <p> elements that contain an <h2> heading inside them",
    ],
    correctAnswer: "All sibling <p> elements that follow an <h2> under the same parent element",
    explanation: "The general sibling combinator (~) matches all sibling elements that appear after the first element under the same parent.",
  },
  {
    courseSlug: "css",
    topicName: "Box Model",
    difficulty: "EASY",
    type: "mcq",
    question: "What are the four components of the standard CSS box model, from inside out?",
    options: [
      "Content, Padding, Border, Margin",
      "Content, Margin, Border, Padding",
      "Padding, Content, Border, Margin",
      "Border, Padding, Content, Margin",
    ],
    correctAnswer: "Content, Padding, Border, Margin",
    explanation: "The CSS box model consists of content in the center, wrapped by padding, border, and outer margin.",
  },
  {
    courseSlug: "css",
    topicName: "Box Model",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "When applying 'box-sizing: border-box', how are the specified width and height calculated?",
    options: [
      "Width includes Content, Padding, and Border",
      "Width includes Content only, with Padding and Border added on top",
      "Width includes Content, Padding, Border, and Margin",
      "Width only applies to the element's background image",
    ],
    correctAnswer: "Width includes Content, Padding, and Border",
    explanation: "In border-box sizing, padding and border are contained within the declared width and height, preventing accidental layout expansion.",
  },
  {
    courseSlug: "css",
    topicName: "Display",
    difficulty: "EASY",
    type: "mcq",
    question: "Which display property value completely hides an element and removes it from the document layout flow?",
    options: ["display: none", "visibility: hidden", "opacity: 0", "filter: blur(100px)"],
    correctAnswer: "display: none",
    explanation: "display: none removes the element from rendering flow entirely, taking up zero physical space on screen.",
  },
  {
    courseSlug: "css",
    topicName: "Display",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "What is the primary difference between 'display: inline' and 'display: inline-block'?",
    options: [
      "inline-block respects specified width and height properties, whereas inline ignores width and height",
      "inline elements start on a new line, whereas inline-block does not",
      "inline-block cannot contain text nodes",
      "inline elements can have vertical margins, while inline-block cannot",
    ],
    correctAnswer: "inline-block respects specified width and height properties, whereas inline ignores width and height",
    explanation: "inline-block elements flow horizontally like inline text, but allow width, height, and vertical margin/padding adjustments.",
  },
  {
    courseSlug: "css",
    topicName: "Position",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "An element with 'position: absolute' is positioned relative to which ancestor?",
    options: [
      "The nearest ancestor element that has a position other than static",
      "Always relative to the <body> element",
      "Always relative to the immediate direct parent element",
      "The root <html> viewport only",
    ],
    correctAnswer: "The nearest ancestor element that has a position other than static",
    explanation: "position: absolute positions an element relative to its closest positioned ancestor (relative, absolute, fixed, or sticky).",
  },
  {
    courseSlug: "css",
    topicName: "Position",
    difficulty: "HARD",
    type: "mcq",
    question: "Why might an element with 'position: sticky; top: 0;' fail to stick when scrolling?",
    options: [
      "An ancestor element has 'overflow: hidden', 'overflow: auto', or 'overflow: scroll' set",
      "Sticky positioning only works inside <table> elements",
      "The element does not have a z-index assigned",
      "The viewport width is greater than 1200px",
    ],
    correctAnswer: "An ancestor element has 'overflow: hidden', 'overflow: auto', or 'overflow: scroll' set",
    explanation: "An ancestor with an overflow property other than visible breaks the scrolling context needed for position: sticky to function.",
  },
  {
    courseSlug: "css",
    topicName: "Flexbox",
    difficulty: "EASY",
    type: "mcq",
    question: "Which CSS Flexbox property aligns flex items along the main axis?",
    options: ["justify-content", "align-items", "align-content", "flex-direction"],
    correctAnswer: "justify-content",
    explanation: "justify-content aligns items along the main axis (horizontal by default in row direction).",
  },
  {
    courseSlug: "css",
    topicName: "Flexbox",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "In CSS Flexbox, what does the shorthand declaration 'flex: 1;' assign to flex-grow, flex-shrink, and flex-basis?",
    options: [
      "flex-grow: 1, flex-shrink: 1, flex-basis: 0%",
      "flex-grow: 1, flex-shrink: 0, flex-basis: auto",
      "flex-grow: 0, flex-shrink: 1, flex-basis: 100px",
      "flex-grow: 1, flex-shrink: 1, flex-basis: auto",
    ],
    correctAnswer: "flex-grow: 1, flex-shrink: 1, flex-basis: 0%",
    explanation: "In standard modern CSS, 'flex: 1;' expands to 'flex: 1 1 0%', allowing the item to grow and shrink proportionally from a zero basis.",
  },
  {
    courseSlug: "css",
    topicName: "Flexbox",
    difficulty: "HARD",
    type: "mcq",
    question: "How can you center an element both horizontally and vertically inside a flex container?",
    code: ".container {\n  display: flex;\n  /* Which rules center the child? */\n}",
    options: [
      "justify-content: center; align-items: center;",
      "align-content: center; text-align: center;",
      "margin: auto 0; flex-align: center;",
      "float: center; vertical-align: middle;",
    ],
    correctAnswer: "justify-content: center; align-items: center;",
    explanation: "justify-content: center centers items along the main axis, and align-items: center centers along the cross axis.",
  },
  {
    courseSlug: "css",
    topicName: "Grid",
    difficulty: "EASY",
    type: "mcq",
    question: "Which CSS property defines the column structure in a CSS Grid container?",
    options: [
      "grid-template-columns",
      "grid-columns",
      "grid-layout-cols",
      "template-columns",
    ],
    correctAnswer: "grid-template-columns",
    explanation: "grid-template-columns defines the line names and track sizing functions of grid columns.",
  },
  {
    courseSlug: "css",
    topicName: "Grid",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "What does the CSS Grid unit '1fr' represent?",
    options: [
      "One fraction of the free, available space in the grid container",
      "One fixed row height based on font size",
      "One frame measurement in CSS animations",
      "One full viewport resolution width",
    ],
    correctAnswer: "One fraction of the free, available space in the grid container",
    explanation: "The fr unit represents a fraction of the unused space available inside the grid container.",
  },
  {
    courseSlug: "css",
    topicName: "Grid",
    difficulty: "HARD",
    type: "mcq",
    question: "What is the difference between 'auto-fill' and 'auto-fit' in repeat(..., minmax(200px, 1fr))?",
    options: [
      "auto-fit collapses empty tracks to 0px so filled tracks expand, while auto-fill preserves empty tracks",
      "auto-fill works with flexbox, while auto-fit is strictly grid",
      "auto-fit is deprecated in modern CSS",
      "auto-fill requires media queries to function",
    ],
    correctAnswer: "auto-fit collapses empty tracks to 0px so filled tracks expand, while auto-fill preserves empty tracks",
    explanation: "auto-fit collapses empty tracks to 0px and stretches actual items to fill container width, while auto-fill keeps empty column slots intact.",
  },
  {
    courseSlug: "css",
    topicName: "Responsive Design",
    difficulty: "EASY",
    type: "mcq",
    question: "Which CSS at-rule is used to apply styles conditionally based on device screen characteristics?",
    options: ["@media", "@screen", "@device", "@viewport"],
    correctAnswer: "@media",
    explanation: "@media rule applies CSS rules only when specified media query criteria (like min-width) match the device.",
  },
  {
    courseSlug: "css",
    topicName: "Media Queries",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "In a mobile-first responsive architecture, which media query pattern is used to add desktop layout enhancements?",
    options: [
      "@media (min-width: 768px)",
      "@media (max-width: 768px)",
      "@media (orientation: mobile)",
      "@media (device-aspect-ratio: 16/9)",
    ],
    correctAnswer: "@media (min-width: 768px)",
    explanation: "Mobile-first CSS writes default styles for small screens without media queries, then uses min-width to introduce larger screen styles.",
  },
  {
    courseSlug: "css",
    topicName: "Variables",
    difficulty: "EASY",
    type: "mcq",
    question: "What is the correct syntax for declaring and referencing a CSS custom property (variable)?",
    code: ":root {\n  --primary: #2563eb;\n}\n.button {\n  background: ???;\n}",
    options: [
      "var(--primary)",
      "$primary",
      "@primary",
      "css(--primary)",
    ],
    correctAnswer: "var(--primary)",
    explanation: "CSS custom properties begin with two hyphens (--name) and are accessed with the var(--name) functional notation.",
  },
  {
    courseSlug: "css",
    topicName: "Specificity",
    difficulty: "HARD",
    type: "mcq",
    question: "Which of the following selector combinations has the greatest specificity value?",
    options: [
      "#nav .item (1 ID, 1 class)",
      ".header .menu .item a (3 classes, 1 element)",
      "ul li.active a (1 class, 3 elements)",
      "body header nav ul li (5 elements)",
    ],
    correctAnswer: "#nav .item (1 ID, 1 class)",
    explanation: "An ID selector (weight 1,0,0) outweighs any number of class (0,1,0) or element (0,0,1) selectors.",
  },

  // ===================== JAVASCRIPT QUESTIONS =====================
  {
    courseSlug: "javascript",
    topicName: "JavaScript Basics",
    difficulty: "EASY",
    type: "mcq",
    question: "Which keyword declares a block-scoped, reassignable variable in modern JavaScript?",
    options: ["let", "const", "var", "def"],
    correctAnswer: "let",
    explanation: "'let' declares a block-scoped variable that can be reassigned, introduced in ECMAScript 2015 (ES6).",
  },
  {
    courseSlug: "javascript",
    topicName: "JavaScript Basics",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "What does the expression 'typeof null' evaluate to in JavaScript?",
    options: ["'object'", "'null'", "'undefined'", "'boolean'"],
    correctAnswer: "'object'",
    explanation: "'typeof null' returns 'object' due to a historical legacy bug in the initial JavaScript implementation that cannot be changed for backwards compatibility.",
  },
  {
    courseSlug: "javascript",
    topicName: "Variables",
    difficulty: "EASY",
    type: "mcq",
    question: "What error is thrown when attempting to reassign a variable declared with 'const'?",
    code: "const pi = 3.14;\npi = 3.14159;",
    options: [
      "TypeError: Assignment to constant variable",
      "ReferenceError: Variable is not defined",
      "SyntaxError: Duplicate identifier",
      "RangeError: Overflow assignment",
    ],
    correctAnswer: "TypeError: Assignment to constant variable",
    explanation: "Variables declared with const are read-only references; reassigning them throws a TypeError.",
  },
  {
    courseSlug: "javascript",
    topicName: "Data Types",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "Which of the following is NOT a primitive data type in JavaScript?",
    options: ["Array", "Symbol", "BigInt", "Undefined"],
    correctAnswer: "Array",
    explanation: "Arrays, Objects, and Functions are reference types (Object sub-types), whereas string, number, bigint, boolean, undefined, symbol, and null are primitives.",
  },
  {
    courseSlug: "javascript",
    topicName: "Operators",
    difficulty: "EASY",
    type: "mcq",
    question: "What is the difference between the '==' and '===' comparison operators?",
    options: [
      "'===' checks both value and data type without coercion, while '==' performs type coercion",
      "'==' is strict comparison, while '===' allows partial matching",
      "'===' is only valid for numbers and booleans",
      "There is no difference in modern ECMAScript",
    ],
    correctAnswer: "'===' checks both value and data type without coercion, while '==' performs type coercion",
    explanation: "Strict equality (===) verifies identical types and values without type conversions.",
  },
  {
    courseSlug: "javascript",
    topicName: "Operators",
    difficulty: "HARD",
    type: "mcq",
    question: "What is the result of 'null ?? 'fallback'' vs 'false ?? 'fallback'' using the nullish coalescing operator?",
    options: [
      "'fallback' and false",
      "'fallback' and 'fallback'",
      "null and false",
      "undefined and 'fallback'",
    ],
    correctAnswer: "'fallback' and false",
    explanation: "The nullish coalescing operator (??) only falls back when the left operand is null or undefined. Boolean false is preserved.",
  },
  {
    courseSlug: "javascript",
    topicName: "Arrow Functions",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "How does the 'this' keyword behave inside an arrow function compared to a standard function?",
    options: [
      "Arrow functions do not bind their own 'this'; they inherit 'this' lexically from the enclosing execution context",
      "Arrow functions always bind 'this' to the global window object",
      "Arrow functions bind 'this' to the element triggering the event",
      "Arrow functions cannot access any outer scope variables",
    ],
    correctAnswer: "Arrow functions do not bind their own 'this'; they inherit 'this' lexically from the enclosing execution context",
    explanation: "Arrow functions capture the 'this' binding of the surrounding lexical context rather than creating their own dynamic 'this'.",
  },
  {
    courseSlug: "javascript",
    topicName: "Arrays",
    difficulty: "EASY",
    type: "mcq",
    question: "Which Array method creates a new array populated with the results of calling a provided function on every element?",
    options: ["map()", "forEach()", "filter()", "push()"],
    correctAnswer: "map()",
    explanation: "Array.prototype.map() returns a brand new transformed array without mutating the original array.",
  },
  {
    courseSlug: "javascript",
    topicName: "Array Methods",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "What is the difference between Array.prototype.slice() and Array.prototype.splice()?",
    options: [
      "slice() returns a shallow copy of a portion of an array without modifying it, while splice() mutates the original array",
      "splice() is non-destructive, while slice() modifies the original array",
      "slice() can only add elements, while splice() can only remove elements",
      "They are aliases for the same underlying operation",
    ],
    correctAnswer: "slice() returns a shallow copy of a portion of an array without modifying it, while splice() mutates the original array",
    explanation: "slice() is an immutable operation returning a copy; splice() modifies the array in place by removing, replacing, or adding elements.",
  },
  {
    courseSlug: "javascript",
    topicName: "Array Methods",
    difficulty: "HARD",
    type: "mcq",
    question: "What will the following code snippet output to the console?",
    code: "const nums = [1, 2, 3, 4];\nconst sum = nums.reduce((acc, curr) => acc + curr, 10);\nconsole.log(sum);",
    options: ["20", "10", "15", "NaN"],
    correctAnswer: "20",
    explanation: "reduce starts with initial value 10: 10 + 1 + 2 + 3 + 4 = 20.",
  },
  {
    courseSlug: "javascript",
    topicName: "Objects",
    difficulty: "EASY",
    type: "mcq",
    question: "Which operator allows safe navigation of deeply nested object properties without throwing an error if a property is null or undefined?",
    code: "const city = user?.address?.city;",
    options: [
      "Optional chaining operator (?.)",
      "Nullish coalescing operator (??)",
      "Spread operator (...)",
      "Ternary operator (? :)",
    ],
    correctAnswer: "Optional chaining operator (?.)",
    explanation: "The optional chaining operator (?.) short-circuits and evaluates to undefined if the reference is nullish, preventing runtime TypeErrors.",
  },
  {
    courseSlug: "javascript",
    topicName: "Closures",
    difficulty: "HARD",
    type: "mcq",
    question: "What is a closure in JavaScript?",
    options: [
      "The combination of a function bundled together with references to its surrounding lexical state",
      "A method to close network sockets when finished",
      "A loop structure that terminates automatically",
      "An anonymous function that executes immediately upon definition",
    ],
    correctAnswer: "The combination of a function bundled together with references to its surrounding lexical state",
    explanation: "A closure gives a function access to its outer scope variables even after the outer function has finished executing.",
  },
  {
    courseSlug: "javascript",
    topicName: "Promises",
    difficulty: "EASY",
    type: "mcq",
    question: "What are the three possible states of a JavaScript Promise?",
    options: [
      "pending, fulfilled, rejected",
      "waiting, resolved, failed",
      "active, complete, error",
      "initialized, running, stopped",
    ],
    correctAnswer: "pending, fulfilled, rejected",
    explanation: "A Promise is always in one of three states: pending (initial), fulfilled (succeeded), or rejected (failed).",
  },
  {
    courseSlug: "javascript",
    topicName: "Async/Await",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "What does an 'async' function always return in JavaScript?",
    options: ["A Promise", "A Callback", "An Observable", "A Generator"],
    correctAnswer: "A Promise",
    explanation: "Functions declared with async always return a Promise, automatically wrapping non-Promise return values in Promise.resolve().",
  },
  {
    courseSlug: "javascript",
    topicName: "DOM Manipulation",
    difficulty: "EASY",
    type: "mcq",
    question: "Which modern DOM method selects the first element matching a specified CSS selector string?",
    options: [
      "document.querySelector()",
      "document.getElement()",
      "document.findCSS()",
      "document.selectOne()",
    ],
    correctAnswer: "document.querySelector()",
    explanation: "document.querySelector() returns the first Element within the document that matches the specified CSS selector.",
  },
  {
    courseSlug: "javascript",
    topicName: "Event Listeners",
    difficulty: "MEDIUM",
    type: "mcq",
    question: "What does the event.preventDefault() method accomplish inside an event handler?",
    options: [
      "It prevents the browser's default action associated with the event from occurring (e.g. following a link or submitting a form)",
      "It stops the event from bubbling up the DOM hierarchy",
      "It disables all other event handlers attached to the element",
      "It deletes the event object from memory",
    ],
    correctAnswer: "It prevents the browser's default action associated with the event from occurring (e.g. following a link or submitting a form)",
    explanation: "event.preventDefault() cancels the default behavior of the browser for that event without stopping event propagation.",
  },
  {
    courseSlug: "javascript",
    topicName: "Hoisting",
    difficulty: "HARD",
    type: "mcq",
    question: "What is the Temporal Dead Zone (TDZ) in JavaScript?",
    options: [
      "The period between entering the scope and the variable declaration where accessing 'let' or 'const' throws a ReferenceError",
      "The duration between sending a fetch request and receiving response headers",
      "The interval during Garbage Collection when script execution pauses",
      "The time taken for setTimeout(..., 0) to enter the event loop",
    ],
    correctAnswer: "The period between entering the scope and the variable declaration where accessing 'let' or 'const' throws a ReferenceError",
    explanation: "Variables declared with let/const exist in the Temporal Dead Zone from the start of the block until the declaration is evaluated.",
  },
];

async function main() {
  console.log("🚀 Starting rich question bank expansion...");

  const courses = await prisma.course.findMany();
  const courseMap = new Map(courses.map((c) => [c.slug, c.id]));

  let totalAdded = 0;

  for (const q of RICH_QUESTIONS) {
    const courseId = courseMap.get(q.courseSlug);
    if (!courseId) {
      console.warn(`Course ${q.courseSlug} not found. Skipping.`);
      continue;
    }

    const slug = slugify(q.topicName);
    // Ensure topic exists
    const topic = await prisma.topic.upsert({
      where: { courseId_slug: { courseId, slug } },
      update: { name: q.topicName },
      create: { courseId, name: q.topicName, slug },
    });

    // Check if question exists
    const existing = await prisma.question.findFirst({
      where: {
        courseId,
        topicId: topic.id,
        question: q.question,
      },
    });

    if (!existing) {
      await prisma.question.create({
        data: {
          courseId,
          topicId: topic.id,
          difficulty: q.difficulty,
          type: q.type,
          question: q.question,
          code: q.code || null,
          options: JSON.stringify(q.options),
          correctAnswer: q.correctAnswer,
          explanation: q.explanation,
          generationSource: "curriculum_engine",
        },
      });
      totalAdded++;
    }
  }

  console.log(`✅ Successfully seeded ${totalAdded} high-quality questions!`);
}

main()
  .catch((err) => {
    console.error("Error seeding rich questions:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
